server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://associations-mysql-db:3306/associations
    username: ${associations_db_user}
    password: ${associations_db_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

