spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${associations_db_user}
    password: ${associations_db_password}
  
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
