server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/associations
    username: ${associations_db_user}
    password: ${associations_db_password}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true     
