server:
  port: 8087
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${auth_db_host}:${auth_db_port}/${auth_db}
    username: ${auth_db_user}
    password: ${auth_db_password}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true 

application:
  security:
    jwt:
      secret-key: ${security_key}
      expiration: ${expiration}

  config:
    associations-url: http://${associations_host}:${associations_port}/api/v1/associations
