server:
  port: 8080 

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: """
            allowedHeaders: "*"
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowCredentials: true
            
      routes:
        - id: associations-service
          uri: lb://associations-service 
          predicates:
            - Path=/api/v1/associations/** 
          filters:
           - AuthenticationFilter
           
        - id: raffles-service-raffles
          uri: lb://raffles-service  
          predicates:
            - Path=/api/v1/raffles/**  
          filters:
           - AuthenticationFilter
           
        - id: raffles-service-s3
          uri: lb://raffles-service 
          predicates:
            - Path=/api/v1/s3/** 
          filters:
           - AuthenticationFilter
           
        - id: tickets-service
          uri: lb://tickets-service 
          predicates:
            - Path=/api/v1/tickets/** 
          filters:
           - AuthenticationFilter
           
        - id: payments-service
          uri: lb://payments-service 
          predicates:
            - Path=/api/v1/payments/** 
          filters:
           - AuthenticationFilter
           
        - id: orders-service
          uri: lb://orders-service 
          predicates:
            - Path=/api/v1/orders/** 
          filters:
           - AuthenticationFilter
           
        - id: notifications-service
          uri: lb://notifications-service 
          predicates:
            - Path=/api/v1/notifications/** 
          filters:
           - AuthenticationFilter
           
        - id: auth-server
          uri: lb://auth-server 
          predicates:
            - Path=/api/v1/auth/** 

application:
  config:
    auth-url: http://${auth_host}:${auth_port}/api/v1/auth
