server:
  port: 8087
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${notifications_db_host}:${notifications_db_port}/${notifications_db}
    username: ${notifications_db_user}
    password: ${notifications_db_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  kafka:
    bootstrap-servers: ${kafka_host}:${kafka_port} 
    consumer:
      group-id: notifications-group 
      auto-offset-reset: earliest 
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted: 
              packages: com.raffleease.common-models.DTO.Kafka 
            type:
              mapping: order-success:com.raffleease.common_models.DTO.Kafka.OrderSuccess
      
  mail:
    host: ${mail_host}
    port: ${mail_port}
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
