server:
  port: 8084
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${orders_db_host}:${orders_db_port}/${orders_db}
    username: ${orders_db_user}
    password: ${orders_db_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
application:
  config:
    tickets-url: http://raffles-service:8082/api/v1/tickets
    stripe-url: http://${payments_host}:${payments_port}/api/v1/stripe
