server:
  port: 8065
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${orders_db_host}:${orders_db_port}/${orders_db}
    username: ${associations_db_user}
    password: ${associations_db_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
application:
  config:
    tickets-url: http://${raffles_host}:${raffles_port}/api/v1/tickets
