server:
  port: 8085
spring:
  data:
    mongodb:
      username: ${payments_db_user}
      password: ${payments_db_password}
      host: ${payments_db_host}
      port: ${payments_db_port}
      database: ${payments_db}
      authentication-database: admin

  kafka:
    producer:
      bootstrap-servers: ${kafka_host}:${kafka_port}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializerapplication
      
  config:
    raffles-url: http://${raffles_host}:${raffles_port}/api/v1/raffles
