server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver    
    url: jdbc:postgresql://${raffles_db_host}:${raffles_db_port}/${raffles_db}
    username: ${raffles_db_user}
    password: ${raffles_db_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  config:
    associations-url: http://${associations_host}:${associations_port}/api/v1/associations
