server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver    
    url: jdbc:postgresql://${raffles_db_host}:${raffles_db_port}/${raffles_db}
    username: ${raffles_db_user}
    password: ${raffles_db_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${kafka_host}:${kafka_port} 
    consumer:
      group-id: raffles-group 
      auto-offset-reset: earliest 
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted: 
              packages: com.raffleease.common_models.DTO.Kafka
            type:
              mapping: modify-availability:com.raffleease.common_models.DTO.Kafka.TicketsAvailabilityRequest

application:
  config:
    associations-url: http://${associations_host}:${associations_port}/api/v1/associations
    tickets-url: http://${tickets_host}:${tickets_port}/api/v1/tickets
