server:
  port: 8086
spring:
  data:
    mongodb:
      username: ${tickets_db_user}
      password: ${tickets_db_password}
      host: ${tickets_db_host}
      port: ${tickets_db_port}
      database: ${tickets_db}
      authentication-database: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

spring:
  kafka:
    bootstrap-servers: ${kafka_host}:${kafka_port} 
    consumer:
      group-id: tickets-group 
      auto-offset-reset: earliest 
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted: 
              packages: com.raffleease.common-models.DTO.Kafka
            type:
              mapping: tickets-release:com.raffleease.common-models.DTO.Tickets.TicketsReleaseRequest
    producer:
      bootstrap-servers: ${kafka_host}:${kafka_port}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer    
